CREATE TABLE website_assistant_settings (
    id INTEGER PRIMARY KEY,
    assistant_name VARCHAR(80) NOT NULL,
    welcome_message VARCHAR(300) NOT NULL,
    prompt_addition TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE website_knowledge_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_type VARCHAR(20) NOT NULL,
    title VARCHAR(160) NOT NULL,
    question VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    keywords VARCHAR(500) NOT NULL,
    enabled BOOLEAN NOT NULL,
    priority INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_website_knowledge_enabled_priority
    ON website_knowledge_entries (enabled, priority DESC, updated_at DESC);

INSERT INTO website_assistant_settings (
    id, assistant_name, welcome_message, prompt_addition, enabled, updated_at
) VALUES (
    1,
    '网站智能助手',
    '你好！我可以介绍首页功能，并帮你找到对应入口。',
    '',
    TRUE,
    CURRENT_TIMESTAMP
);

INSERT INTO website_knowledge_entries (
    entry_type, title, question, content, keywords, enabled, priority, created_at, updated_at
) VALUES (
    'INFO',
    '个人导航首页',
    '',
    '这是一个个人化网站聚合首页，用来集中访问站长的博客、常用工具、服务器面板、小游戏和其他个人项目。首页支持日间和夜间主题，可以通过搜索框按网站名称、描述和关键词筛选卡片。主要入口包括：博客、AI 助手平台、工具合集、Hugo 博客、服务器面板、Gitee/CICD、密码管理器、方方小游戏、存档管理、远行手记和应用桌面。顶部还有烟花秀、圣诞树、地球仪、布丁跳舞和鼓点练习等趣味入口。外部系统的账号、权限和具体操作方式不属于公开网站资料。',
    '首页,导航,网站,功能,搜索,主题',
    TRUE,
    100,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

INSERT INTO website_knowledge_entries (
    entry_type, title, question, content, keywords, enabled, priority, created_at, updated_at
) VALUES (
    'FAQ',
    '如何找到站点入口',
    '我怎么找到想访问的站点？',
    '在首页搜索框输入功能名称或关键词，再点击匹配的网站卡片。也可以直接询问右下角的网站助手。',
    '入口,卡片,搜索,在哪里,怎么找',
    TRUE,
    90,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
